import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { twMerge } from 'tailwind-merge'
import Link from 'next/link'

// 프리텐다드 폰트 선언
const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const headerButtonClass = 'rounded bg-gray-200 px-3 py-1 sm:block' // 반복되는 클래스 분리
const sidebarClass = 'w-full flex-shrink-0 bg-gray-900 p-4 text-white lg:w-64' // 사이드바 클래스

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={twMerge(pretendard.className, 'bg-gray-100 text-gray-900')}>
        <div className="flex flex-col lg:flex-row">
          {/* 사이드바 네비게이션 */}
          <aside className={sidebarClass}>
            <h2 className="text-xl font-bold">Logo</h2>
            <nav className="flex flex-col space-y-4">
              <Link
                href="/dashboard"
                passHref
                className="flex items-center space-x-2 hover:text-gray-300"
              >
                <span>🏠</span>
                <span>Dashboard</span>
              </Link>
              <Link href="#" passHref className="flex items-center space-x-2 hover:text-gray-300">
                <span>📊</span>
                <span>Analytics</span>
              </Link>
              <Link href="#" passHref className="flex items-center space-x-2 hover:text-gray-300">
                <span>⚙️</span>
                <span>Settings</span>
              </Link>
            </nav>
          </aside>

          {/* 메인 컨텐츠 영역 */}
          <div className="flex flex-1 flex-col">
            {/* 헤더 (고정) */}
            <header className="flex items-center justify-between bg-white p-4 shadow">
              <h1 className="text-lg font-semibold">Dashboard</h1>
              <button className={headerButtonClass}>🔔</button> {/* 알림 버튼 */}
            </header>

            {/* 스크롤 가능한 콘텐츠 영역 */}
            <main className="flex-1 overflow-auto bg-gray-100 p-6">{children}</main>
          </div>
        </div>
      </body>
    </html>
  )
}
